### ISSUE TITLE
Add ability to use find and replace interpolation

### ISSUE THREAD

**Issue by Harrisonbro** [buildkite/interpolate#8]
It would be very helpful to be able to do simple find and replace with interpolation. My use case, for example, would be to use the Git branch name as a Docker image tag but to do so I need to replace certain characters that are valid in Git but not in Docker — e.g., replace forward slashes with dashes.

It would be great to be able to do something like this:

```
- label: "Push images tagged with Git branch"
  plugins:
    - docker-compose#v3.7.0:
        config: buildkite/docker/compose.yml
        push:
          - foo:123456789.dkr.ecr.eu-west-2.amazonaws.com/foo:${BUILDKITE_BRANCH//\\//--}
```

There you can see the desired interpolation that converts a `/` character to `--`
